src/news/urls.py
from django.conf.urls import url

from .views import (
    news_list,
    news_detail,
)

urlpatterns = [
    url(r'^$', news_list, name='the-news'),
    url(r'^(?P<slug>[\w-]+)$', news_detail, name='detail'),
]

src/triumph/urls.py
# coding: utf-8

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from core import views as core_views
from triumph import views

handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^robots.txt$', views.robots_txt, name='robots_txt'),
    url(r'^sitemap.xml$', views.sitemap_xml, name='sitemap_xml'),
    
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^news/', include("news.urls", namespace='news')),
    url(r'^galleries/', include("galleries.urls", namespace='galleries')),
    url(r'^videos/', include("videos.urls", namespace='videos')),
    url(r'^articles/', include("articles.urls", namespace='articles')),
    url(r'^dance-styles/', include("styles.urls", namespace='styles')),
    url(r'^', include("attainments.urls", namespace='attainments')),
    url(r'^school/', include("school.urls", namespace='school')),
    url(r'^', include("timetable.urls", namespace='timetable')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    
    urlpatterns += [
        url(r'^400/$', core_views.bad_request, {'exception': 'test'}),
        url(r'^403/$', core_views.permission_denied, {'exception': 'test'}),
        url(r'^403_csrf/$', core_views.csrf_failure, {'force_display': True}),
        url(r'^404/$', core_views.page_not_found, {'exception': 'test'}),
        url(r'^500/$', core_views.server_error),
    ]
    
    import debug_toolbar
    
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/school/models.py
from ckeditor.fields import RichTextField
from django.db import models

from core.models import ImageMixin, SEOMixin
from core.utils import upload_location


class School(SEOMixin):
    title = models.CharField(verbose_name=u'Название', max_length=60,
                             default=u'Труимф')
    about = RichTextField()
    promo = RichTextField()

    def has_related_object(self):
        return hasattr(self, 'contact') and self.car is not None

    def __unicode__(self):
        return '{}'.format(self.title)

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name_plural = u"Школа"


class Coach(models.Model):
    last_name = models.CharField(verbose_name=u'Фамилия', max_length=20)
    first_name = models.CharField(verbose_name=u'Имя', max_length=20)
    avatar = models.ImageField(upload_to=upload_location,
                               null=True, blank=True,
                               width_field="width_field",
                               height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    title = RichTextField()
    quote = RichTextField()
    school = models.ForeignKey(School, blank=True, null=True)

    def __unicode__(self):
        return '{} {}'.format(self.last_name, self.first_name)

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)

    class Meta:
        verbose_name_plural = u"Тренеры"
        ordering = ["id"]


class Photo(ImageMixin):
    school = models.ForeignKey(School)

    def __unicode__(self):
        return '{}'.format(self.id)

    def __str__(self):
        return '{}'.format(self.id)


class DanceHall(models.Model):
    description = RichTextField()
    school = models.OneToOneField(School, related_name='hall')

    def get_school(self):
        return u'{}'.format(self.school.title)

    def __unicode__(self):
        return '{}'.format(self.id)

    def __str__(self):
        return '{}'.format(self.id)

    class Meta:
        verbose_name_plural = u"Танцевальный зал"


class Image(ImageMixin):
    dance_hall = models.ForeignKey(DanceHall)

    def __unicode__(self):
        return '{}'.format(self.id)

    def __str__(self):
        return '{}'.format(self.id)


class Contact(SEOMixin):
    school = models.OneToOneField(School, related_name='contact')
    country = models.CharField(verbose_name=u'Страна', max_length=255)
    city = models.CharField(verbose_name=u'Город', max_length=255)
    street = models.CharField(verbose_name=u'Улица', max_length=255)
    postcode = models.CharField(verbose_name=u'Почтовый индекс', max_length=255)
    phones = models.CharField(verbose_name=u'Телефоны', max_length=255)
    work_time = models.CharField(verbose_name=u'Режим работы', max_length=255)

    def __unicode__(self):
        return "{}, {}, {}".format(self.country, self.city, self.street)

    def __str__(self):
        return "{}, {}, {}".format(self.country, self.city, self.street)

    class Meta:
        verbose_name_plural = u"Контакты"

src/triumph/views.py
# coding: utf-8

from django.shortcuts import render

from school.models import School


def home(request):
    school_queryset = School.objects.all()
    if school_queryset:
        instance = school_queryset[0]
    else:
        instance = None
    context = {}
    if instance:
        context['instance'] = instance
        context['browser_title'] = instance.browser_title
        context['h1'] = instance.h1
        context['keywords'] = instance.key_words
        context['head_description'] = instance.head_description
    return render(request, 'home.html', context)


def robots_txt(request):
    return render(
        request, 'robots.txt', {}, content_type='text/plain')


def sitemap_xml(request):
    return render(
        request, 'sitemap.xml', {}, content_type='text/plain')

src/triumph/templates/403_csrf.html
{% extends "base.html" %}


{% block content %}
{% endblock %}

src/triumph/templates/about_us.html
{% extends "base.html" %}

{% block content %}
<section class="about section_indent">
    <div class="block-content__title block-content__title_indent">
        <h2>О клубе спортивного танца "Триумф"</h2>
    </div>
    <div class="about__detail">
        {{ instance.about|safe }}
    </div>
    <div class="about__gallery">
        {% for obj in instance.photo_set.all %}
        <div class="gallery__instance">
            <img class="img-thumbnail" src="{{ obj.image.url }}" alt="{{ obj.name }}">
        </div>
        {%cycle "" "" "" "" "</div><div class='about__gallery'>" %}
        {% endfor %}
    </div>
</section>
<section itemscope itemtype="http://schema.org/Person" class="coaches section_indent">
    <div class="block-content__title block-content__title_indent">
        <h2>Наши тренеры</h2>
    </div>
    {% for obj in instance.coach_set.all %}
    <div class="row row__coaches_indent">
        <div class="col-sm-5">
            <div class="block-avatar">
                <div class="block-avatar__photo_wrapper">
                    <div class="block-avatar__photo">
                        <img class="img-responsive" src="{{ obj.avatar.url }}" alt="{{ obj.last_name }}">
                    </div>
                </div>
                <div class="block-avatar__decor">
                    <span itemprop="name" class="fontsforweb_fontid_6771">{{ obj.first_name }} {{ obj.last_name }}</span>
                </div>
            </div>

        </div>
        <div class="col-sm-7">
            <div class="block-content__list-description">
                <!--<div class="list-description__name list-description__name_indent">-->
                    <!--<h4 class="fontsforweb_fontid_6771">{{ obj.first_name }} {{ obj.last_name }}</h4>-->
                <!--</div>-->
                <div class="list-description__title list-description__title_indent">
                    <span itemprop="jobTitle">{{ obj.title | safe }}</span>
                </div>
                <div class="list-description__quote">
                    {{ obj.quote | safe }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</section>
<section class="dance-hall section_indent">
    <div class="block-content__title block-content__title_indent">
        <h2>Танцевальный зал</h2>
    </div>
    <div class="row">
        <div class="dance-hall__detail">
            {{ instance.hall.description|safe }}
        </div>
    </div>
    <div class="dance-hall__gallery">
        <div class="row">
            {% for obj in instance.hall.image_set.all %}
                <div class="col-sm-6 dance-hall__gallery_indent">
                    <div class="gallery__image">
                        <img class="img-responsive" src="{{ obj.image.url }}" alt="{{ obj.name }}">
                    </div>
                </div>
            {%cycle "" "</div><div class='row'>" %}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

src/triumph/templates/articles_list.html
{% extends "base.html" %}

{% block content %}
<div class="block-content__title block-content__title_indent">
    <h2>Статьи и полезная информация</h2>
</div>
{% for obj in object_list %}
<div class="row">
    <div class="col-sm-4">
        {% if obj.cover_image %}
        <img class="block-content__list-img img-responsive" src="{{ obj.cover_image.url }}" alt="{{ obj.name }}">
        {% else %}
        <p>no photo</p>
        {% endif %}
    </div>
    <div class="col-sm-8 reset-indents">
        <div class="block-content__list-description">
            <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h3>
            <small>{{ obj.date_created|date:"d.m.Y" }}</small>
            <p class="list-description__content">{{ obj.content | striptags | safe | truncatechars:330 }}</p>
        </div>
    </div>
</div>
<hr>
{% endfor %}

{% include "el_pagination/show_pages.html" %}
{% endblock content %}

src/triumph/templates/attainment_list.html
{% extends "base.html" %}

{% block jquery %}
    $('.slider-nav').slick({
      slidesToShow: 4,
      slidesToScroll: 1,
      dots: false,
      centerMode: true,
      focusOnSelect: true,
      variableWidth: true
    });

    function changeImageSource(src) {
        $("#main-view").attr("src", src)
    }
    $slider = $('.slider-nav');
    $slider.on( "click", function(event) {
        var elem = $(event.target);
        if (elem.hasClass('img-responsive')) {
          changeImageSource(elem.attr('src'));
        }
        return false;
      });
{% endblock jquery %}

{% block content %}
<section class="attaintment section_indent">
    <div class="block-content__title block-content__title_indent">
    <h2>{{ title }}</h2>
    </div>
    <div class="attaintment__intro">
        {{ instance.intro | safe }}
    </div>
    {% if instance.diploma_set.all %}
        <div class="attaintment__diploma attaintment__diploma_indent">
            <div class="slider-nav">
                {% for obj in instance.diploma_set.all %}
                <div class="slide clearfix">
                    <img class="img-responsive" src="{{ obj.image.url }}" alt="{{ obj.name }}">
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div class="attaintment__content">
        {{ instance.content | safe }}
    </div>
    <div class="attaintment__photo">
        <div class="slide__main-view">
            <img id="main-view" src="{{ cover_photo.image.url }}" class="img-responsive" alt="{{ cover_photo.name }}">
        </div>
        <div class="slider-nav">
            {% for obj in instance.photo_set.all %}
            <div class="slide clearfix">
                <img class="img-responsive" src="{{ obj.image.url }}" alt="{{ obj.name }}">
            </div>
            {% endfor %}
        </div>
    </div>


</section>
{% endblock content %}

src/triumph/templates/contacts.html
{% extends "base.html" %}

{% block external_script %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCF4mIl_ZnqwKe0R4pNAlwXRhhCXGf7rAQ&libraries=places"></script>
{% endblock %}

{% block jquery %}
    var icon = {
        url: '/static/img/google-maps-pin-green.png',
        scaledSize: new google.maps.Size(30, 50)
    }
    var $container = $('#map');
    $container.height($container.width()*0.7 + 'px');

    geocoder = new google.maps.Geocoder();
    var mapOptions = {
      zoom: 16,
      center: {lat: 49.9935, lng: 36.2304},
      scrollwheel: false, //отключение/включение масштабирования колесиком мыши + swipe
      zoomControl: true //отключение/включение панели масштабирования
    }
    map = new google.maps.Map(document.getElementById('map'), mapOptions);

    (function codeAddress() {
        var country = '{{ contacts.country }}',
            city = '{{ contacts.city }}',
            street = '{{ contacts.street }}';
        var address = country + ' ' + city + ' ' + street;
        geocoder.geocode( { 'address': address}, function(results, status) {
          if (status == 'OK') {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                position: results[0].geometry.location,
                map: map,
                title: 'Танцевальная школа "Триумф"',
                icon: icon
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
    })();

{% endblock jquery %}


{% block content %}

<div class="block-content__title block-content__title_indent">
    <h2>{{ title }}</h2>
</div>
<div class="contacts">
    <div class="row">
        <div class="col-sm-3"><span>Телефоны:</span></div>
        <div class="col-sm-9"><p>{{ instance.phones }}</p></div>
    </div>
    <div class="row">
        <div class="col-sm-3"><span>Время работы:</span></div>
        <div class="col-sm-9"><p>{{ instance.work_time }}</p></div>
    </div>
    <div class="row">
        <div class="col-sm-3"><span>Адрес:</span></div>
        <div class="col-sm-9"><p>{{ contacts.country }}, {{ contacts.city }}, {{ contacts.street }}</p></div>
    </div>
</div>
<div class="map-block">
    <h4 class="text-center">Схема проезда</h4>
    <div id="map" style="width:100%;"></div>
</div>
{% endblock content %}

src/triumph/templates/galleries_list.html
{% extends "base.html" %}

{% block content %}
<div class="block-content__title block-content__title_indent">
    <h2>{{ title }}</h2>
</div>
<div class="gallery">
    <div class="row">
    {% for obj in object_list %}
        {% if obj.photo_set.all %}
        <div class="col-sm-4">
            <div class="thumbnail__block">
                <a href="{{ obj.get_absolute_url }}" class="thumbnail">
                    <img class="block-content__list-img" src="{{ obj.get_cover_photo.image.url }}" alt="{{ obj.get_cover_photo.name }}">
                </a>
                <a href="{{ obj.get_absolute_url }}" class="reference">
                    <h5 class="text-center">{{ obj.title }}</h5>
                </a>
            </div>
        </div>
        {% endif %}
    {%cycle "" "" "</div><div class='row'>" %}
    {% endfor %}
</div>
</div>


{% include "el_pagination/show_pages.html" %}
{% endblock content %}

src/triumph/templates/gallery_detail.html
{% extends "base.html" %}

{% block jquery %}
    $('.slider-nav').slick({
      slidesToShow: 3,
      slidesToScroll: 1,
      dots: false,
      centerMode: true,
      focusOnSelect: true
    });

function changeImageSource(src) {
    $("#main-view").attr("src", src)
}
$slider = $('.slider-nav');
$slider.on( "click", function(event) {
    var elem = $(event.target);
    if (elem.hasClass('img-responsive')) {
      changeImageSource(elem.attr('src'));
    }
    return false;
  });
{% endblock jquery %}

{% block content %}
<div class="block-content__title block-content__title_indent">
    <h2>{{ title }}</h2>
</div>
    <div class="slide__main-view clearfix">
        <img id="main-view" src="{{ cover_photo.image.url }}" class="img-responsive" alt="{{ cover_photo.name }}">
    </div>
<div class="slider-nav">
    {% for obj in instance.photo_set.all %}
    <div class="slide clearfix">
        <img class="img-responsive" src="{{ obj.image.url }}" alt="{{ obj.name }}">
    </div>
    {% endfor %}
</div>
{% endblock content %}

src/triumph/templates/news_detail.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-10 blogShort">
        <div class="news-detail">
            <h2 class="news-detail__title">{{ title }}</h2>
            {% if instance.image %}
            <img src="{{ instance.image.url }}" alt="{{ instance.title }}" class="pull-left img-responsive postImg img-thumbnail">
            {% endif %}
            <article>
                <p>{{ instance.content | safe }}</p>
            </article>
        </div>


    </div>
</div>
{% endblock content %}

src/triumph/templates/news_list.html
{% extends "base.html" %}

{% block content %}
<div class="block-content__title block-content__title_indent">
    <h2>Новости клуба спортивного танца “Триумф”</h2>
</div>
{% for obj in object_list %}
<div class="row">
    <div class="col-sm-4">
        {% if obj.image %}
        <img class="block-content__list-img img-responsive" src="{{ obj.image.url }}" alt="{{ obj.title }}">
        {% else %}
        <p>no photo</p>
        {% endif %}
    </div>
    <div class="col-sm-8">
        <div class="block-content__list-description">
            <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h3>
            <small>{{ obj.date_created|date:"d.m.Y" }}</small>
            <p class="list-description__content">{{ obj.content | striptags | safe | truncatechars:420 }}</p>
        </div>
    </div>
</div>
<hr>
{% endfor %}

{% include "el_pagination/show_pages.html" %}
{% endblock content %}

src/triumph/templates/styles_detail.html
{% extends "base.html" %}

{% block jquery %}
$('.slider-nav').slick({
slidesToShow: 3,
slidesToScroll: 1,
dots: false,
centerMode: true,
focusOnSelect: true
});

function changeImageSource(src) {
$("#main-view").attr("src", src)
}
$slider = $('.slider-nav');
$slider.on( "click", function(event) {
var elem = $(event.target);
if (elem.hasClass('img-responsive')) {
changeImageSource(elem.attr('src'));
}
return false;
});
{% endblock jquery %}

{% block content %}
<div class="dance-styles-detail clearfix">
    {% if instance.photo_set.all %}
        <div class="dance-styles-detail__carousel dance-styles-detail__carousel_indent">
            <div class="slide__main-view">
                <img id="main-view" src="{{ cover_photo.image.url }}" class="img-responsive" alt="{{ cover_photo.name }}">
            </div>
            <div class="slider-nav">
                {% for obj in instance.photo_set.all %}
                <div class="slide clearfix">
                    <img class="img-responsive" src="{{ obj.image.url }}" alt="{{ obj.name }}">
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div class="dance-styles-detail__info">
        <div class="dance-styles-detail__title ">
            <h3 class="fontsforweb_fontid_6771">{{ title }}</h3>
        </div>
        <p class="dance-styles-detail__text">
            {{ instance.content|safe }}
        </p>
    </div>
    {% if instance.style_set.all %}
        <div class="dance-styles-detail__substyles">
            <div class="dance-styles-detail__title ">
                <h3 class="fontsforweb_fontid_6771">Направления</h3>
            </div>
            <div class="row">
                {% for obj in instance.style_set.all %}
                <div class="col-sm-6 dance-style_indent">
                    {% include 'includes/style_card.html' with style=obj %}
                </div>
                {%cycle "" "</div><div class='row'>" %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

src/triumph/templates/styles_list.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block content %}
<div class="row">
    {% for obj in object_list %}
    <div class="col-sm-6 dance-style_indent">
        {% include 'includes/style_card.html' with style=obj %}
    </div>
    {%cycle "" "</div><div class='row'>" %}
    {% endfor %}
</div>
{% include "el_pagination/show_pages.html" %}
{% endblock content %}

src/triumph/templates/time_table.html
{% extends "base.html" %}


{% block jquery %}
    <!--var timetable = new Timetable(),-->
        <!--startTime = '{{ timetable.start }}',-->
        <!--endTime = '{{ timetable.end }}',-->
        <!--workDays = '{{ days }}',-->
        <!--startTimeHour = startTime.split(':')[0],-->
        <!--endTimeHour = endTime.split(':')[0];-->

    <!--timetable.setScope(parseInt(startTimeHour, 10), parseInt(endTimeHour, 10));-->
    <!--timetable.addDays(workDays.split(','));-->
    <!--{% for event in events %}-->
        <!--var _start = '{{ event.start }}'.split(':');-->
        <!--var start = new Date;-->
        <!--start.setHours(_start[0]);-->
        <!--start.setMinutes(_start[1]);-->

        <!--var _finish = '{{ event.finish }}'.split(':');-->
        <!--var finish = new Date;-->
        <!--finish.setHours(_finish[0]);-->
        <!--finish.setMinutes(_finish[1]);-->
        <!--{% for day in event.day.all %}-->
            <!--timetable.addEvent('{{ event.name }}', '{{ event.color }}', '{{ day.title }}', start, finish, '{{ event.coach.last_name }}', '{{ event.additional_info }}', { url: '#' });-->
        <!--{% endfor %}-->

    <!--{% endfor %}-->
    <!--//timetable.addEvent('контемп', 'среда', new Date(2017,7,17,11,00), new Date(2017,7,17,12,45), { url: '#' });-->
    <!--var _timetable = '{{ timetable.start }}';-->


    <!--var renderer = new Timetable.Renderer(timetable);-->
    <!--renderer.draw('.timetable');-->


    {% for schedule in schedules %}
        var $wrap = $('.timetable-wrapper'),
            timetableData = {},
            usageId = "timetable" + {{ forloop.counter }},
            timetableBlock = document.createElement('div');

        $(timetableBlock)
            .addClass('timetable-block')
            .appendTo($wrap);

        var titleDiv =  document.createElement('div'),
            title = document.createElement('h2');

        $(titleDiv)
            .addClass('block-content__title')
            .appendTo(timetableBlock);

        $(title)
            .html('{{ schedule.room }}')
            .appendTo(titleDiv);

        var wrapperDiv = document.createElement('div');
        $(wrapperDiv)
            .addClass('wrapper');

        $(wrapperDiv).append('<div id=' + usageId + ' class="timetable"></div>');
        $(wrapperDiv).appendTo(timetableBlock);

        timetableData.startTime = '{{ schedule.start }}';
        timetableData.endTime = '{{ schedule.end }}';
        timetableData.work_days = [];

        {% for day in schedule.work_days.all %}
            timetableData.work_days.push('{{ day.title }}');
        {% endfor %}

        timetableData.events = [];

        {% for event in schedule.event_set.all %}
            var _start = '{{ event.start }}'.split(':');
            var start = new Date;
            start.setHours(_start[0]);
            start.setMinutes(_start[1]);
            var _finish = '{{ event.finish }}'.split(':');
            var finish = new Date;
            finish.setHours(_finish[0]);
            finish.setMinutes(_finish[1]);
            {% for day in event.day.all %}
                timetableData.events.push({
                    'start': start,
                    'finish': finish,
                    'color': '{{ event.color }}',
                    'name': '{{ event.name }}',
                    'day': '{{ day.title }}',
                    'coach': '{{ event.coach.last_name }}',
                    'info': '{{ event.additional_info }}'
                });
            {% endfor %}
        {% endfor %}
        $('#' + usageId).generateTimetable(timetableData);
    {% endfor %}
{% endblock jquery %}


{% block content %}
<div class="timetable-wrapper">
</div>
{% endblock content %}

src/triumph/templates/videos_list.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}
<div class="block-content__title block-content__title_indent">
    <h2>{{ title }}</h2>
</div>
<div class="gallery">
    <div class="row gallery__row_indent">
        {% for obj in object_list %}
        <div class="col-sm-4">
            <div class="thumbnail__block">
                {% video obj.video as video %}
                <a href="{{ obj.get_absolute_url }}" class="thumbnail">
                    <img src="{{ video.thumbnail }}" class="img-responsive" alt="{{ video.title }}"/>
                </a>
                {% endvideo %}
                <a href="{{ obj.get_absolute_url }}" class="reference">
                    <span>{{ obj.title }}</span>
                </a><br>
                <small>{{ obj.date_created|date:"d.m.Y" }}</small>
            </div>
        </div>
        {%cycle "" "" "</div><div class='row gallery__row_indent'>" %}{% endfor %}
    </div>
</div>


{% include "el_pagination/show_pages.html" %}
{% endblock content %}